/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apotek;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DataPenjualan extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[] {
    "KODE OBAT","NAMA OBAT","JUMLAH OBAT","HARGA", "TGL PEMBELIAN"
    });
    /**
     * Creates new form DataPenjualan
     */
    public DataPenjualan() {
        initComponents();
        tblPenjualan.setModel(tableModel);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodeObat = new javax.swing.JTextField();
        namaObat = new javax.swing.JTextField();
        jumlahObat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(56, 118, 191));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PENJUALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel2.setText("Kode Obat");

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel3.setText("Nama Obat");

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Obat");

        kodeObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kodeObatMouseClicked(evt);
            }
        });
        kodeObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeObatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal");

        btnSimpan.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenjualan);

        btnKembali.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kodeObat)
                                    .addComponent(namaObat)
                                    .addComponent(jumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(harga)
                                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCari))
                                    .addComponent(btnSimpan)))))
                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(kodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus)
                            .addComponent(btnBatal)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnSimpan)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(false);
        kodeObat.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        Object data[] = new Object[4];
        int row = tblPenjualan.getSelectedRow();
        try {
            String sql = "select * from datapenjualan where kodeObat='"+tableModel.getValueAt(row, 0).toString()+"' ";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
        while (rs.next()) {
            kodeObat.setText(rs.getString("kodeObat"));
            namaObat.setText(rs.getString("namaObat"));
            jumlahObat.setText(rs.getString("jumlahObat"));
            harga.setText(rs.getString("harga"));
            tanggal.setDate(rs.getDate("tanggal"));
        }
        } catch (SQLException ex) {
        System.out.println("ERROR di Queri IsiTable"
                + ex.getMessage());
        }
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            updateStokObat(kodeObat.getText(), Integer.parseInt(jumlahObat.getText()));
            String sql = "INSERT INTO datapenjualan "
                    + "(kodeObat, namaObat, jumlahObat, harga, tanggal) "
                    + "VALUES (?, ?, ?, ?, ?)";
        
                    java.sql.Connection conn = (Connection) Koneksi.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
                    pst.setString(1, kodeObat.getText());
                    pst.setString(2, namaObat.getText());
                    pst.setString(3, jumlahObat.getText());
                    pst.setString(4, harga.getText());
        
                    java.sql.Date tanggalKedaluwarsa = new java.sql.Date(tanggal.getDate().getTime());
                    pst.setDate(5, tanggalKedaluwarsa);

                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
                    tampilkanData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void updateStokObat(String kodeObat, int jumlahTerjual) {
        try {
            String sql = "UPDATE dataobat SET stok = stok - ? WHERE kodeObat = ?";
            Connection conn = Koneksi.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, jumlahTerjual);
            pst.setString(2, kodeObat);

            pst.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR dalam mengurangi stok obat: " + ex.getMessage());
        }
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "DELETE FROM datapenjualan "
                + "WHERE kodeObat='"+kodeObat.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampilkanData();
            setAwalForm();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR di Query IsiTable " + ex.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            updateStokObat(kodeObat.getText(), Integer.parseInt(jumlahObat.getText()));
            String sql = "UPDATE datapenjualan SET "
                    + "namaObat=?, "
                    + "jumlahObat=?, "
                    + "harga=?, "
                    + "tanggal=? "
                    + "WHERE kodeObat=?";
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, namaObat.getText());
            pst.setString(2, jumlahObat.getText());
            pst.setString(3, harga.getText());

            if (tanggal.getDate() != null) {
                java.sql.Date tanggalKedaluwarsa = new java.sql.Date(tanggal.getDate().getTime());
                pst.setDate(4, tanggalKedaluwarsa);
            } else {
                pst.setNull(4, java.sql.Types.DATE);
            }

            pst.setString(5, kodeObat.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            tampilkanData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR di Query IsiTable " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_btnCariActionPerformed

    private void kodeObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kodeObatMouseClicked
        // TODO add your handling code here:
        // Saat kode obat diklik, tampilkan data obat yang sesuai
    String kodeObatInput = kodeObat.getText();
    
    // Query untuk mendapatkan data obat berdasarkan kode obat
    String query = "SELECT namaObat, harga FROM dataobat WHERE kodeObat = ?";
    
    try {
        Connection conn = Koneksi.configDB();
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, kodeObatInput);
        ResultSet rs = pst.executeQuery();
        
        // Jika data obat ditemukan
        if (rs.next()) {
            // Set nilai field namaObat dan harga sesuai dengan data obat yang ditemukan
            namaObat.setText(rs.getString("namaObat"));
            harga.setText(rs.getString("harga"));
        } else {
            // Jika data obat tidak ditemukan, kosongkan field namaObat dan harga
            namaObat.setText("");
            harga.setText("");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
    }
    }//GEN-LAST:event_kodeObatMouseClicked

    private void kodeObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeObatActionPerformed

    public void setAwalForm(){
        kodeObat.setText("");
        namaObat.setText("");
        jumlahObat.setText("");
        harga.setText("");
        tanggal.setDate(null);
        kodeObat.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnCari.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false); 
    }
    
    public void bersihTable() {
        int row = tblPenjualan.getRowCount() - 1;
        while (row >= 0) {
            tableModel.removeRow(row);
            row--;
        }
    }
    
    public void tampilkanData(){
    tableModel.setRowCount(0);
    bersihTable();
    Object data[] = new Object[6];
    try {
        String sql = "select * from datapenjualan";
        java.sql.Connection conn=(Connection)Koneksi.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet rs=stm.executeQuery(sql);
        while (rs.next()) {
            data [0] = rs.getString("kodeObat");
            data [1] = rs.getString("namaObat");
            data [2] = rs.getString("jumlahObat");
            data [3] = rs.getString("harga");
            data [4] = rs.getString("tanggal");
            tableModel.addRow(data);
        }
    } catch (SQLException ex) {
        System.out.println("ERROR di Queri IsiTable" + ex.getMessage());
    }
    
}
    private void cari(){
        int row = tblPenjualan.getRowCount();
        for(int a = 0 ; a < row ; a++){
            tableModel.removeRow(0);
        }
        
        String cari = txt_cari.getText();
        
        String query = "SELECT * FROM `datapenjualan` WHERE `kodeObat`  LIKE '%"+cari+"%' OR `namaObat` LIKE '%"+cari+"%' ";
                
       try{
            java.sql.Connection conn=(Connection)Koneksi.configDB();
           Statement sttmnt = conn.createStatement();
           ResultSet rslt = sttmnt.executeQuery(query);
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String kodeObat = rslt.getString("kodeObat");
                    String namaObat = rslt.getString("namaObat");
                    String jumlahObat = rslt.getString("jumlahObat");
                    String harga = rslt.getString("harga");
                    String tanggal = rslt.getString("tanggal");
                    
                //masukan semua data kedalam array
                String[] data = {kodeObat,namaObat,jumlahObat, harga, tanggal};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                tableModel.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tblPenjualan.setModel(tableModel);
           
        
    }catch(Exception e){
           System.out.println(e);
    }
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahObat;
    private javax.swing.JTextField kodeObat;
    private javax.swing.JTextField namaObat;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
