/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apotek;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DataObat extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[] {
    "KODE OBAT","NAMA OBAT","STOK","JENIS OBAT","HARGA", "EXP"
    });
    /**
     * Creates new form DataObat
     */
    public DataObat() {
        initComponents();
        tblObat.setModel(tableModel);
        tampilkanData();
        jenisObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Capsul", "Cair", "Tablet", "Salep"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kodeObat = new javax.swing.JTextField();
        namaObat = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        jenisObat = new javax.swing.JComboBox<>();
        harga = new javax.swing.JTextField();
        tglKedaluwarsa = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(56, 118, 191));

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA OBAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel1.setText("Kode Obat");

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel2.setText("Nama Obat");

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel3.setText("Stok");

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Obat");

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Kedaluwarsa");

        jenisObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblObat);

        btnSimpan.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaObat)
                            .addComponent(stok)
                            .addComponent(kodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCari)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jenisObat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(harga)
                                .addComponent(tglKedaluwarsa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .addComponent(btnSimpan))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnKembali))
                            .addComponent(jScrollPane1))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jenisObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglKedaluwarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO dataobat "
                + "(kodeObat, namaObat, stok, jenisObat, harga, tglKedaluwarsa) "
                + "VALUES (?, ?, ?, ?, ?, ?)";
        
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, kodeObat.getText());
        pst.setString(2, namaObat.getText());
        pst.setString(3, stok.getText());
        pst.setString(4, (String) jenisObat.getSelectedItem());
        pst.setString(5, harga.getText());
        
        java.sql.Date tanggalKedaluwarsa = new java.sql.Date(tglKedaluwarsa.getDate().getTime());
        pst.setDate(6, tanggalKedaluwarsa);

        pst.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
        tampilkanData();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "UPDATE dataobat SET "
                + "namaObat=?, "
                + "stok=?, "
                + "jenisObat=?, "
                + "harga=?, "
                + "tglKedaluwarsa=? "
                + "WHERE kodeObat=?";
        
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, namaObat.getText());
        pst.setString(2, stok.getText());
        pst.setString(3, (String) jenisObat.getSelectedItem());
        pst.setString(4, harga.getText());

        // Periksa apakah tglKedaluwarsa tidak null sebelum mengambil nilainya
        if (tglKedaluwarsa.getDate() != null) {
            java.sql.Date tanggalKedaluwarsa = new java.sql.Date(tglKedaluwarsa.getDate().getTime());
            pst.setDate(5, tanggalKedaluwarsa);
        } else {
            pst.setNull(5, java.sql.Types.DATE);
        }

        pst.setString(6, kodeObat.getText());

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        tampilkanData();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "ERROR di Query IsiTable " + ex.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "DELETE FROM dataobat "
                + "WHERE kodeObat='"+kodeObat.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampilkanData();
            setAwalForm();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR di Query IsiTable " + ex.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObatMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(false);
        kodeObat.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        Object data[] = new Object[5];
        int row = tblObat.getSelectedRow();
        try {
            String sql = "select * from dataobat where kodeObat='"+tableModel.getValueAt(row, 0).toString()+"' ";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
        while (rs.next()) {
            kodeObat.setText(rs.getString("kodeObat"));
            namaObat.setText(rs.getString("namaObat"));
            stok.setText(rs.getString("stok"));
            jenisObat.setSelectedItem(rs.getString("jenisObat"));
            harga.setText(rs.getString("harga"));
            tglKedaluwarsa.setDate(rs.getDate("tglKedaluwarsa"));
        }
        } catch (SQLException ex) {
        System.out.println("ERROR di Queri IsiTable"
                + ex.getMessage());
        }
    }//GEN-LAST:event_tblObatMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_btnCariActionPerformed
    
    public void bersihTable() {
        int row = tblObat.getRowCount() - 1;
        while (row >= 0) {
            tableModel.removeRow(row);
            row--;
        }
    }
    
    public void tampilkanData(){
    tableModel.setRowCount(0);
    bersihTable();
    Object data[] = new Object[6];
    try {
        String sql = "select * from dataobat";
        java.sql.Connection conn=(Connection)Koneksi.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet rs=stm.executeQuery(sql);
        while (rs.next()) {
            data [0] = rs.getString("kodeObat");
            data [1] = rs.getString("namaObat");
            data [2] = rs.getString("stok");
            data [3] = rs.getString("jenisObat");
            data [4] = rs.getString("harga");
            data [5] = rs.getString("tglKedaluwarsa");
            tableModel.addRow(data);
        }
    } catch (SQLException ex) {
        System.out.println("ERROR di Queri IsiTable" + ex.getMessage());
    }
}
    public void setAwalForm(){
        kodeObat.setText("");
        namaObat.setText("");
        stok.setText("");
        jenisObat.setSelectedItem("");
        harga.setText("");
        tglKedaluwarsa.setDate(null);
        kodeObat.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);        
    }
   
    private void cari(){
        int row = tblObat.getRowCount();
        for(int a = 0 ; a < row ; a++){
            tableModel.removeRow(0);
        }
        
        String cari = txt_cari.getText();
        
        String query = "SELECT * FROM `dataobat` WHERE `kodeObat`  LIKE '%"+cari+"%' OR `namaObat` LIKE '%"+cari+"%' ";
                
       try{
            java.sql.Connection conn=(Connection)Koneksi.configDB();
           Statement sttmnt = conn.createStatement();
           ResultSet rslt = sttmnt.executeQuery(query);
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String kodeObat = rslt.getString("kodeObat");
                    String namaObat = rslt.getString("namaObat");
                    String stok = rslt.getString("stok");
                    String jenisObat = rslt.getString("jenisObat");
                    String harga = rslt.getString("harga");
                    String tglKedaluwarsa = rslt.getString("tglKedaluwarsa");
                    
                //masukan semua data kedalam array
                String[] data = {kodeObat,namaObat,stok,jenisObat, harga, tglKedaluwarsa};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                tableModel.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                tblObat.setModel(tableModel);
           
        
    }catch(Exception e){
           System.out.println(e);
    }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisObat;
    private javax.swing.JTextField kodeObat;
    private javax.swing.JTextField namaObat;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tblObat;
    private com.toedter.calendar.JDateChooser tglKedaluwarsa;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
